spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Bookify


  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}
